In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind

In [2]:
pollster_df = pd.read_csv(r'C:\Users\Lyons\OneDrive\Desktop\IML-FALL2025---Voter-Bias\webscraped_data\pollsters_2014_2024.csv')
mi_cutoff_df = pd.read_csv(r'C:\Users\Lyons\OneDrive\Desktop\IML-FALL2025---Voter-Bias\voter_team\voter_team_cutoff50_weighted_michigan.csv')

In [3]:
pollster_df = pollster_df.rename(columns = {'pollster_name' : 'voter'})
pollster_df['voter'] = pollster_df['voter'].str.lower()
pollster_df['voter'] = pollster_df['voter'].str.replace(' ', '-')
pollster_df

               voter                affiliation          city state  year
0          adam-jude          The Seattle Times       Seattle    WA  2014
1        adam-sparks         Daily News Journal  Murfreesboro    TN  2014
2        adam-zucker         CBS Sports Network        Summit    NJ  2014
3    bill-rabinowitz      The Columbus Dispatch      Columbus    OH  2014
4       bob-asmussen     Champaign News-Gazette     Champaign    IL  2014
..               ...                        ...           ...   ...   ...
704    steve-wiseman             The Herald-Sun        Durham    NC  2024
705   steven-johnson   Fort Worth Star-Telegram     Arlington    TX  2024
706       tom-murphy  Arkansas Democrat-Gazette   Little Rock    AR  2024
707      trevor-hass                 Boston.com        Boston    MA  2024
708       zach-klein                        WSB       Atlanta    GA  2024

[709 rows x 5 columns]

In [ ]:
df = mi_cutoff_df.merge(pollster_df[['voter', 'city', 'state', 'year']], on = 'voter', how = 'left')
df.year = df.year.astype('str').str.replace('.0', '')
df

,voter,team,bias1,bias2,bias3,bias0_ap,bias0_mean,n,city,state,year
0,soren-petro,michigan-wolverines,-0.208513,-0.421360,-0.399139,-2.358491,-3.907962,53,Leawood,KS,2017
1,soren-petro,michigan-wolverines,-0.208513,-0.421360,-0.399139,-2.358491,-3.907962,53,Leawood,KS,2018
2,soren-petro,michigan-wolverines,-0.208513,-0.421360,-0.399139,-2.358491,-3.907962,53,Leawood,KS,2019
3,soren-petro,michigan-wolverines,-0.208513,-0.421360,-0.399139,-2.358491,-3.907962,53,Leawood,KS,2020
4,nathan-baird,michigan-wolverines,-0.142241,-0.532013,-0.514203,-1.240741,-2.894981,54,Cleveland,OH,2019
...,...,...,...,...,...,...,...,...,...,...,...
368,dylan-sinn,michigan-wolverines,0.188521,-0.111259,-0.087568,1.980769,0.073654,52,Fort Wayne,IN,2018
369,dylan-sinn,michigan-wolverines,0.188521,-0.111259,-0.087568,1.980769,0.073654,52,Fort Wayne,IN,2019
370,dylan-sinn,michigan-wolverines,0.188521,-0.111259,-0.087568,1.980769,0.073654,52,Fort Wayne,IN,2020
371,dylan-sinn,michigan-wolverines,0.188521,-0.111259,-0.087568,1.980769,0.073654,52,Fort Wayne,IN,2021
372,dylan-sinn,michigan-wolverines,0.188521,-0.111259,-0.087568,1.980769,0.073654,52,Fort Wayne,IN,2024

In [5]:
team_state_map = {
    'alabama' : 'AL', 
    'michigan' : 'MI', 
    'ohio-state' : 'OH', 
    'lsu' : 'LA', 
    'oklahoma' : 'OK'
}

bias_column = 'bias1' # add more columns? 
results = []

for team, team_state in team_state_map.items():
    temp = df.copy()
    temp['in_state'] = temp['state'].eq(team_state)

    summary = {
        "team": team,
        "team_state": team_state,
        "avg_bias_in_state": temp[temp["in_state"]][bias_column].mean(),
        "avg_bias_out_state": temp[temp["in_state"] == False][bias_column].mean(),
        "n_in_state": temp[temp["in_state"]].shape[0],
        "n_out_state": temp[temp["in_state"] == False].shape[0]
    }
    results.append(summary)

analysis_df = pd.DataFrame(results)
analysis_df

,team,team_state,avg_bias_in_state,avg_bias_out_state,n_in_state,n_out_state
0,alabama,AL,NaN,0.041267,0,373
1,michigan,MI,0.032922,0.041404,6,367
2,ohio-state,OH,-0.018733,0.045578,25,348
3,lsu,LA,-0.028073,0.043374,11,362
4,oklahoma,OK,0.079669,0.040533,7,366